# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-16 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batteryPages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patentgroup',
            old_name='group',
            new_name='name',
        ),
    ]
