# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-17 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteryPages', '0002_auto_20171116_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=100)),
                ('jurisdiction', models.CharField(max_length=100)),
                ('work_product', models.TextField()),
                ('notes', models.TextField()),
                ('status', models.TextField()),
                ('counsel', models.TextField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
    ]
