# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-17 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteryPages', '0003_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='counsel',
            field=models.CharField(max_length=300),
        ),
    ]
