# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-24 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batteryPages', '0006_auto_20171124_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audioclip',
            old_name='tag',
            new_name='tagName',
        ),
        migrations.AddField(
            model_name='audiotag',
            name='title',
            field=models.CharField(default='', max_length=75),
            preserve_default=False,
        ),
    ]
