# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-30 04:37
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('batteryPages', '0008_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=''),
            preserve_default=False,
        ),
    ]
